# Generated by Django 6.0.3 on 2026-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_systeminstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminstruction',
            name='name',
            field=models.CharField(default='categorize_joblisting', max_length=100),
            preserve_default=False,
        ),
    ]
