# Generated by Django 6.0.3 on 2026-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_systeminstruction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='score',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
