# Generated by Django 6.0.3 on 2026-03-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_joblisting_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='YoE'),
        ),
    ]
