# Generated by Django 6.0.3 on 2026-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_joblisting_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
