# Generated by Django 6.0.3 on 2026-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_joblisting_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
