# Generated by Django 6.0.3 on 2026-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_joblisting_posted_at_alter_joblisting_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='posted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
