# Generated by Django 6.0.3 on 2026-03-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_jobmatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmatch',
            options={'verbose_name_plural': 'Job matches'},
        ),
    ]
