# Generated by Django 6.0.3 on 2026-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_jobmatch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
