# Generated by Django 6.0.4 on 2026-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_joblisting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.URLField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
