# Generated by Django 6.0.4 on 2026-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_joblisting_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='portal',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='systeminstruction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='systeminstruction',
            name='description',
            field=models.TextField(default='Default system instruction for LLM job data extraction'),
            preserve_default=False,
        ),
    ]
