# Generated by Django 6.0.4 on 2026-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_joblisting_options_alter_portal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='scrape_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='scraper_class',
            field=models.CharField(blank=True, choices=[('PracujplScraper', 'PracujplScraper'), ('JustJoinITScraper', 'JustJoinITScraper'), ('TheProtocolITScraper', 'TheProtocolITScraper')], max_length=50, null=True),
        ),
    ]
