services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi_service:
    build: ./fastapi_app
    ports:
      - "8001:8000"
    volumes:
      - ./fastapi_app:/app
      - ./job_finder:/app/job_finder  # <--- This maps Django project inside FastAPI
      - ./media:/app/media  # Shared volume for PDFs
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  django:
    build: ./job_finder
    volumes:
      - ./job_finder:/app
      - ./media:/app/media  # Same shared volume
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      - FASTAPI_URL=http://fastapi_service:8000
    depends_on:
      db:
        condition: service_healthy
      fastapi_service:
        condition: service_started

volumes:
  postgres_data: